apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: souravdeveloper/udemy-course
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: udemy
            - name: 'MONGO_URI'
              value: 'mongodb+srv://sourav:<password>@cluster0.btqfage.mongodb.net/course?retryWrites=true&w=majority'
            - name: JWT_EXP
              value: '90d'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: course-srv
spec:
  selector:
    app: course
  ports:
    - name: course
      protocol: TCP
      port: 3000
      targetPort: 3000
