import Head from 'next/head';
import Banner from '../components/Banner';
import CourseList from '../components/CourseList';
import Header from '../components/Header/Header';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Udemy Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.container}>
        {/* <Banner /> */}
        <CourseList />
      </main>
    </div>
  );
}
