apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: souravdeveloper/auth
          env:
            - name: 'MONGO_URI'
              value: 'mongodb+srv://Sourav:<password>@cluster0.dczxv.mongodb.net/auth?retryWrites=true&w=majority'
            - name: JWT_EXP
              value: '90d'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      port: 3000
      protocol: TCP
      targetPort: 3000
